# Generated by Django 2.2.4 on 2019-08-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='context',
            new_name='content',
        ),
    ]
