# Generated by Django 2.2.4 on 2019-08-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190804_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type_name',
            new_name='blog_type',
        ),
    ]
