# Generated by Django 2.2.4 on 2019-08-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190812_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
